# all_tests_debian:
#   image: debian:stable
#   script:
#   - apt-get update -q
#   - apt-get install -qy python3-pip python3-numpy python3-scipy python3-h5py ipython3 python3-natsort python3-sklearn python3-dill python3-ipython-genutils python3-matplotlib python3-skimage python3-pint python3-requests python3-tqdm python3-traits python3-toolz python3-jupyter-client python3-ipython python3-ipykernel python3-pandas python3-patsy python3-pyqt5
#   - apt-get install -qy python3-sympy --no-install-recommends
#   - apt-get install -qy python3-pytest python3-pytest-cov xvfb
#   - pip3 install .
#   - pip3 install opencv-python
#   - pip3 install hyperspy
#   - pip3 install tomopy
#   - pip3 install astra-toolbox
#   - xvfb-run -a --server-args="-screen 0, 1024x768x24" python3 -m pytest --doctest-modules --cov=tomotools tomotools/
#   - xvfb-run -a --server-args="-screen 0, 1024x768x24" python3 -m pytest --doctest-glob="*.rst" doc/

image: continuumio/miniconda3:latest

# tests:
#     stage: test
#     script:
#     - conda create --name test_env
#     - source activate test_env
#     - conda install -c conda-forge hyperspy
#     - conda install -c conda-forge opencv
#     - conda install -c conda-forge tomopy
#     - conda install -c astra-toolbox astra-toolbox
#     - python setup.py install
#     - cd tests && pytest .

flake8_checks:
    image: continuumio/miniconda3:latest
    stage: test
    script:
    - conda install flake8
    - flake8 --exclude=api.py tomotools/

pydocstyle_checks:
    image: continuumio/miniconda3:latest
    stage: test
    script:
    - conda install pydocstyle
    - pydocstyle tomotools/
    allow_failure: true
