before_script:
    - conda create --name test_env
    - source activate test_env

stages:
    - build
    - test

pytests:
    image: continuumio/anaconda3:latest
    stage: test
    script:
    - conda config --add channels conda-forge
    - conda config --add channels astra-toolbox
    - apt-get update
    - apt-get install libgl1-mesa-dev -y
    - conda install hyperspy opencv tomopy astra-toolbox pytest
    - python setup.py install
    - pytest .

flake8_checks:
    image: continuumio/miniconda3:latest
    stage: build
    script:
    - conda install flake8
    - flake8 --exclude=api.py tomotools/

pydocstyle_checks:
    image: continuumio/miniconda3:latest
    stage: build
    script:
    - conda install pydocstyle
    - pydocstyle tomotools/
    allow_failure: true
