image: aaherzing/tomotools:latest

stages:
    - build
    - test

pytests:
    stage: test
    script:
    - python setup.py install
    - pytest .

flake8_checks:
    # image: continuumio/miniconda3:latest
    stage: build
    script:
    # - conda install flake8
    - flake8 --exclude=api.py tomotools/

pydocstyle_checks:
    # image: continuumio/miniconda3:latest
    stage: build
    script:
    # - conda install pydocstyle
    - pydocstyle tomotools/
    allow_failure: true
