image: aaherzing/tomotools:latest

stages:
    - test

pytests:
    stage: test
    script:
    - python setup.py install
    - pytest --doctest-modules tomotools/


flake8_checks:
    stage: test
    script:
    - flake8 --exclude=api.py tomotools/

pydocstyle_checks:
    stage: test
    script:
    - pydocstyle tomotools/
    allow_failure: true
