all_tests_debian:
   image: debian:stable
   script:
   - apt-get update -q
   - apt-get install -qy python3-pip python3-numpy python3-scipy python3-h5py ipython3 python3-natsort python3-sklearn python3-dill python3-ipython-genutils python3-matplotlib python3-skimage python3-pint python3-requests python3-tqdm python3-traits python3-toolz python3-jupyter-client python3-ipython python3-ipykernel python3-pandas python3-patsy python3-pyqt5 python3-hyperspy
   - apt-get install -qy python3-sympy --no-install-recommends
   - apt-get install -qy python3-pytest python3-pytest-cov xvfb
   - apt-get install libopencv-dev python3-opencv
   - pip3 install .
   - xvfb-run -a --server-args="-screen 0, 1024x768x24" python3 -m pytest --doctest-modules --cov=tomotools tomotools/
   - xvfb-run -a --server-args="-screen 0, 1024x768x24" python3 -m pytest --doctest-glob="*.rst" doc/

flake8_checks:
    image: debian:stable
    script:
    - apt-get update -q
    - apt-get install -qy python3-flake8
    - python3 -m flake8 --exclude=api.py tomotools/

pydocstyle_checks:
    image: debian:stable
    script:
    - apt-get update -q
    - apt-get install -qy python3-pip
    - pip3 install pydocstyle
    - python3 -m pydocstyle tomotools/
    allow_failure: true
